package io.github.kylosonic.proxytunnel.core

/**
 * Generates the configuration file hev-socks5-tunnel reads.
 *
 * The keys and their layout are taken from the engine's own documented example
 * (https://github.com/heiher/hev-socks5-tunnel), and the addresses here must match
 * what the `VpnService.Builder` is configured with or the tunnel will carry
 * nothing.
 *
 * ## Secrets
 *
 * The password ends up in this file in plain text, because the engine takes a
 * config *path*. That is a real difference from the iOS side, where the password
 * never leaves the Keychain. Mitigations, all of which the app actually performs:
 *
 *   * the file is written to the app's private `filesDir`, which no other app can
 *     read without root;
 *   * it is written with owner-only permissions;
 *   * it is deleted as soon as the tunnel stops.
 *
 * Nothing logs it, and the config text is never put in an Intent extra or a
 * diagnostic export.
 */
object HevConfig {

    /** Must match `VpnService.Builder.addAddress` in the tunnel service. */
    const val TUN_IPV4 = "198.18.0.1"
    const val TUN_IPV4_PREFIX = 30
    const val TUN_IPV6 = "fc00::1"
    const val TUN_IPV6_PREFIX = 126

    const val DEFAULT_MTU = 1500

    const val FILE_NAME = "hev-socks5-tunnel.yml"

    /**
     * YAML single-quoted scalar.
     *
     * The only escape inside single quotes is a doubled quote, and line breaks are
     * removed before quoting. A value containing a newline would otherwise be folded
     * by YAML into a *different* string than the one stored, and a pasted password
     * containing `\n  udp: 'off'` would be a way to inject a second config key. With
     * both rules applied, no value can escape its own scalar.
     */
    fun singleQuote(value: String): String {
        val flattened = value.replace("\r", "").replace("\n", "").replace("\u0000", "")
        return "'" + flattened.replace("'", "''") + "'"
    }

    fun yaml(
        host: String,
        port: Int,
        username: String?,
        password: String?,
        mtu: Int = DEFAULT_MTU,
        logLevel: String = "warn",
        udpMode: String = "udp"
    ): String {
        val builder = StringBuilder()
        builder.append("# Generated by ProxyTunnel. Deleted when the tunnel stops.\n")
        builder.append("tunnel:\n")
        builder.append("  mtu: ").append(mtu).append('\n')
        builder.append("  ipv4: ").append(singleQuote(TUN_IPV4)).append('\n')
        builder.append("  ipv6: ").append(singleQuote(TUN_IPV6)).append('\n')
        builder.append("  icmp: ").append(singleQuote("off")).append('\n')
        builder.append('\n')
        builder.append("socks5:\n")
        builder.append("  address: ").append(singleQuote(host)).append('\n')
        builder.append("  port: ").append(port).append('\n')
        // UDP through the SOCKS5 association, which is what makes QUIC, HTTP/3 and
        // UDP games work — something the iOS implementation cannot do for HTTP
        // proxies and only does for SOCKS5.
        builder.append("  udp: ").append(singleQuote(udpMode)).append('\n')
        if (!username.isNullOrEmpty()) {
            builder.append("  username: ").append(singleQuote(username)).append('\n')
        }
        if (!password.isNullOrEmpty()) {
            builder.append("  password: ").append(singleQuote(password)).append('\n')
        }
        builder.append('\n')
        builder.append("misc:\n")
        builder.append("  task-stack-size: 86016\n")
        builder.append("  tcp-buffer-size: 65536\n")
        builder.append("  max-session-count: 0\n")
        builder.append("  connect-timeout: 10000\n")
        builder.append("  log-level: ").append(singleQuote(logLevel)).append('\n')
        builder.append("  log-file: null\n")
        return builder.toString()
    }

    /**
     * A description of the config with the credential removed, for the diagnostics
     * screen. Never call this on the real file's contents without masking.
     */
    fun describeRedacted(host: String, port: Int, hasCredential: Boolean, mtu: Int = DEFAULT_MTU): List<String> = listOf(
        "Tunnel MTU: $mtu",
        "Tunnel addresses: $TUN_IPV4/$TUN_IPV4_PREFIX, $TUN_IPV6/$TUN_IPV6_PREFIX",
        "Upstream: SOCKS5 ${ProxyProfile.formatEndpoint(host, port)}",
        "Upstream credentials: ${if (hasCredential) "present (kept out of this report)" else "none"}",
        "UDP: relayed through the SOCKS5 association"
    )
}
